#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ilmbase
Version  : 2.2.1
Release  : 2
URL      : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz
Source0  : http://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz
Summary  : Base math and exception libraries
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ilmbase-lib
Requires: ilmbase-license
BuildRequires : buildreq-cmake

%description
ABOUT THE ILMBASE LIBRARIES
----------------------------
Half is a class that encapsulates our 16-bit floating-point format.

%package dev
Summary: dev components for the ilmbase package.
Group: Development
Requires: ilmbase-lib
Provides: ilmbase-devel

%description dev
dev components for the ilmbase package.


%package lib
Summary: lib components for the ilmbase package.
Group: Libraries
Requires: ilmbase-license

%description lib
lib components for the ilmbase package.


%package license
Summary: license components for the ilmbase package.
Group: Default

%description license
license components for the ilmbase package.


%prep
%setup -q -n ilmbase-2.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537214999
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1537214999
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ilmbase
cp COPYING %{buildroot}/usr/share/doc/ilmbase/COPYING
cp LICENSE %{buildroot}/usr/share/doc/ilmbase/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/OpenEXR/Iex.h
/usr/include/OpenEXR/IexBaseExc.h
/usr/include/OpenEXR/IexErrnoExc.h
/usr/include/OpenEXR/IexExport.h
/usr/include/OpenEXR/IexForward.h
/usr/include/OpenEXR/IexMacros.h
/usr/include/OpenEXR/IexMathExc.h
/usr/include/OpenEXR/IexMathFloatExc.h
/usr/include/OpenEXR/IexMathFpu.h
/usr/include/OpenEXR/IexMathIeeeExc.h
/usr/include/OpenEXR/IexNamespace.h
/usr/include/OpenEXR/IexThrowErrnoExc.h
/usr/include/OpenEXR/IlmBaseConfig.h
/usr/include/OpenEXR/IlmThread.h
/usr/include/OpenEXR/IlmThreadExport.h
/usr/include/OpenEXR/IlmThreadForward.h
/usr/include/OpenEXR/IlmThreadMutex.h
/usr/include/OpenEXR/IlmThreadNamespace.h
/usr/include/OpenEXR/IlmThreadPool.h
/usr/include/OpenEXR/IlmThreadSemaphore.h
/usr/include/OpenEXR/ImathBox.h
/usr/include/OpenEXR/ImathBoxAlgo.h
/usr/include/OpenEXR/ImathColor.h
/usr/include/OpenEXR/ImathColorAlgo.h
/usr/include/OpenEXR/ImathEuler.h
/usr/include/OpenEXR/ImathExc.h
/usr/include/OpenEXR/ImathExport.h
/usr/include/OpenEXR/ImathForward.h
/usr/include/OpenEXR/ImathFrame.h
/usr/include/OpenEXR/ImathFrustum.h
/usr/include/OpenEXR/ImathFrustumTest.h
/usr/include/OpenEXR/ImathFun.h
/usr/include/OpenEXR/ImathGL.h
/usr/include/OpenEXR/ImathGLU.h
/usr/include/OpenEXR/ImathHalfLimits.h
/usr/include/OpenEXR/ImathInt64.h
/usr/include/OpenEXR/ImathInterval.h
/usr/include/OpenEXR/ImathLimits.h
/usr/include/OpenEXR/ImathLine.h
/usr/include/OpenEXR/ImathLineAlgo.h
/usr/include/OpenEXR/ImathMath.h
/usr/include/OpenEXR/ImathMatrix.h
/usr/include/OpenEXR/ImathMatrixAlgo.h
/usr/include/OpenEXR/ImathNamespace.h
/usr/include/OpenEXR/ImathPlane.h
/usr/include/OpenEXR/ImathPlatform.h
/usr/include/OpenEXR/ImathQuat.h
/usr/include/OpenEXR/ImathRandom.h
/usr/include/OpenEXR/ImathRoots.h
/usr/include/OpenEXR/ImathShear.h
/usr/include/OpenEXR/ImathSphere.h
/usr/include/OpenEXR/ImathVec.h
/usr/include/OpenEXR/ImathVecAlgo.h
/usr/include/OpenEXR/half.h
/usr/include/OpenEXR/halfExport.h
/usr/include/OpenEXR/halfFunction.h
/usr/include/OpenEXR/halfLimits.h
/usr/lib64/libHalf.so
/usr/lib64/libIex.so
/usr/lib64/libIexMath.so
/usr/lib64/libIlmThread.so
/usr/lib64/libImath.so
/usr/lib64/pkgconfig/IlmBase.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libHalf.so.23
/usr/lib64/libHalf.so.23.0.0
/usr/lib64/libIex-2_2.so.23
/usr/lib64/libIex-2_2.so.23.0.0
/usr/lib64/libIexMath-2_2.so.23
/usr/lib64/libIexMath-2_2.so.23.0.0
/usr/lib64/libIlmThread-2_2.so.23
/usr/lib64/libIlmThread-2_2.so.23.0.0
/usr/lib64/libImath-2_2.so.23
/usr/lib64/libImath-2_2.so.23.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/ilmbase/COPYING
/usr/share/doc/ilmbase/LICENSE
