#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB02B1CDFA2F82257 (nick@ilm.com)
#
Name     : ilmbase
Version  : 2.3.0
Release  : 5
URL      : https://github.com/openexr/openexr/releases/download/v2.3.0/ilmbase-2.3.0.tar.gz
Source0  : https://github.com/openexr/openexr/releases/download/v2.3.0/ilmbase-2.3.0.tar.gz
Source99 : https://github.com/openexr/openexr/releases/download/v2.3.0/ilmbase-2.3.0.tar.gz.sig
Summary  : Base math and exception libraries
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ilmbase-lib = %{version}-%{release}
Requires: ilmbase-license = %{version}-%{release}
BuildRequires : buildreq-cmake
Patch1: CVE-2018-18443.patch

%description
The IlmBase Libraries
=====================
The IlmBase libraries include the following:

%package dev
Summary: dev components for the ilmbase package.
Group: Development
Requires: ilmbase-lib = %{version}-%{release}
Provides: ilmbase-devel = %{version}-%{release}
Requires: ilmbase = %{version}-%{release}

%description dev
dev components for the ilmbase package.


%package lib
Summary: lib components for the ilmbase package.
Group: Libraries
Requires: ilmbase-license = %{version}-%{release}

%description lib
lib components for the ilmbase package.


%package license
Summary: license components for the ilmbase package.
Group: Default

%description license
license components for the ilmbase package.


%prep
%setup -q -n ilmbase-2.3.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562091185
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1562091185
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ilmbase
cp LICENSE %{buildroot}/usr/share/package-licenses/ilmbase/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/OpenEXR/Iex.h
/usr/include/OpenEXR/IexBaseExc.h
/usr/include/OpenEXR/IexErrnoExc.h
/usr/include/OpenEXR/IexExport.h
/usr/include/OpenEXR/IexForward.h
/usr/include/OpenEXR/IexMacros.h
/usr/include/OpenEXR/IexMathExc.h
/usr/include/OpenEXR/IexMathFloatExc.h
/usr/include/OpenEXR/IexMathFpu.h
/usr/include/OpenEXR/IexMathIeeeExc.h
/usr/include/OpenEXR/IexNamespace.h
/usr/include/OpenEXR/IexThrowErrnoExc.h
/usr/include/OpenEXR/IlmBaseConfig.h
/usr/include/OpenEXR/IlmThread.h
/usr/include/OpenEXR/IlmThreadExport.h
/usr/include/OpenEXR/IlmThreadForward.h
/usr/include/OpenEXR/IlmThreadMutex.h
/usr/include/OpenEXR/IlmThreadNamespace.h
/usr/include/OpenEXR/IlmThreadPool.h
/usr/include/OpenEXR/IlmThreadSemaphore.h
/usr/include/OpenEXR/ImathBox.h
/usr/include/OpenEXR/ImathBoxAlgo.h
/usr/include/OpenEXR/ImathColor.h
/usr/include/OpenEXR/ImathColorAlgo.h
/usr/include/OpenEXR/ImathEuler.h
/usr/include/OpenEXR/ImathExc.h
/usr/include/OpenEXR/ImathExport.h
/usr/include/OpenEXR/ImathForward.h
/usr/include/OpenEXR/ImathFrame.h
/usr/include/OpenEXR/ImathFrustum.h
/usr/include/OpenEXR/ImathFrustumTest.h
/usr/include/OpenEXR/ImathFun.h
/usr/include/OpenEXR/ImathGL.h
/usr/include/OpenEXR/ImathGLU.h
/usr/include/OpenEXR/ImathHalfLimits.h
/usr/include/OpenEXR/ImathInt64.h
/usr/include/OpenEXR/ImathInterval.h
/usr/include/OpenEXR/ImathLimits.h
/usr/include/OpenEXR/ImathLine.h
/usr/include/OpenEXR/ImathLineAlgo.h
/usr/include/OpenEXR/ImathMath.h
/usr/include/OpenEXR/ImathMatrix.h
/usr/include/OpenEXR/ImathMatrixAlgo.h
/usr/include/OpenEXR/ImathNamespace.h
/usr/include/OpenEXR/ImathPlane.h
/usr/include/OpenEXR/ImathPlatform.h
/usr/include/OpenEXR/ImathQuat.h
/usr/include/OpenEXR/ImathRandom.h
/usr/include/OpenEXR/ImathRoots.h
/usr/include/OpenEXR/ImathShear.h
/usr/include/OpenEXR/ImathSphere.h
/usr/include/OpenEXR/ImathVec.h
/usr/include/OpenEXR/ImathVecAlgo.h
/usr/include/OpenEXR/half.h
/usr/include/OpenEXR/halfExport.h
/usr/include/OpenEXR/halfFunction.h
/usr/include/OpenEXR/halfLimits.h
/usr/lib64/libHalf.so
/usr/lib64/libIex.so
/usr/lib64/libIexMath.so
/usr/lib64/libIlmThread.so
/usr/lib64/libImath.so
/usr/lib64/pkgconfig/IlmBase.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libHalf.so.24
/usr/lib64/libHalf.so.24.0.0
/usr/lib64/libIex-2_3.so.24
/usr/lib64/libIex-2_3.so.24.0.0
/usr/lib64/libIexMath-2_3.so.24
/usr/lib64/libIexMath-2_3.so.24.0.0
/usr/lib64/libIlmThread-2_3.so.24
/usr/lib64/libIlmThread-2_3.so.24.0.0
/usr/lib64/libImath-2_3.so.24
/usr/lib64/libImath-2_3.so.24.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ilmbase/LICENSE
